version: '3.8'

services:
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - devnet
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions

  volumes:
    sonarqube_data:
    sonarqube_logs:
    sonarqube_extensions:

  backend:
    image: timmyngn/my-backend:${VERSION}
    container_name: my-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
      - devnet
    depends_on:
      - sonarqube
    restart: unless-stopped

  frontend:
    image: timmyngn/my-frontend:${VERSION}
    container_name: my-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - devnet
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - devnet
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    networks:
      - devnet
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - devnet
    restart: unless-stopped

networks:
  devnet: