version: '3.8'

services:
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - devnet

  backend:
    image: timmyngn/my-backend:${VERSION}
    container_name: my-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
      - devnet
    depends_on:
      - sonarqube
    restart: unless-stopped

  frontend:
    image: timmyngn/my-frontend:${VERSION}
    container_name: my-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - devnet
    restart: unless-stopped

networks:
  devnet: