sonar.projectKey=film-streaming-platform
sonar.projectName=film streaming platform
sonar.projectVersion=1.0

sonar.sources=backend/src
sonar.exclusions=**/node_modules/**,**/tests/**,**/coverage/**

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info