sonar.projectKey=film-streaming-platform
sonar.projectName=film streaming platform
sonar.projectVersion=1.0
sonar.sources=src
sonar.tests=tests
sonar.exclusions=**/node_modules/**,**/tests/**,**/coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=test-results/junit.xml
sonar.host.url=http://sonarqube:9000